#!/bin/sh
#
# This script randomizes root password.
#

# Ensure runtime variables are sourced.
if [ -z ${infrac+x} ]; then
	printf "Environment variable `infrac` not set.\n" 1>&2
	exit 1
fi
. "$(dirname $infrac)/infrac.rtvar"

# Main
if [ $# -eq 1 ]; then
	USERNAME=$1

	printf "[${INFO_COLOR}INFO${END_COLOR}] Generating $USERNAME's random password...\n "
	
	PASSWORD=$($INFRAC_LIB_DIR/generate-password 64)
	
	printf "\n"
	
	echo "$PASSWORD\n$PASSWORD" | passwd $USERNAME > /dev/null 2>&1
	ERROR_CODE=$?
	
	if [ $ERROR_CODE -ne 0 ]; then
		echo_error "Changing $USERNAME's password to \"$PASSWORD\" failed. ($ERROR_CODE)."
		exit 1
	else
		echo_info "$USERNAME's password: $PASSWORD."
	fi
	
	exit 0
else
	echo_error "No username specified. Call with a username please."
	exit 1
fi