#!/bin/sh
#
# This script generates a random password.
#

# Ensure runtime variables are sourced.
if [ -z ${infrac+x} ]; then
	printf "Environment variable `infrac` not set.\n" 1>&2
	exit 1
fi
. "$(dirname $infrac)/infrac.rtvar"

# Main
LENGTH=$1
[ "$LENGTH" = "" ] && LENGTH=16
tr -dc A-Za-z0-9_ < /dev/urandom | head -c ${LENGTH} | xargs

exit 0