#!/bin/sh
#
# This script validates the service name
#

# Ensure runtime variables are sourced.
if [ -z ${infrac+x} ]; then
	printf "Environment variable `infrac` not set.\n" 1>&2
	exit 1
fi
. "$(dirname $infrac)/infrac.rtvar"

# Main
if [ -z ${INFRAC_SERVICES_DIR+X} ]; then       
	echo_error "INFRAC_SERVICES_DIR not defined."
	exit 1
fi


if [ $? -ne 0 ]; then exit 1; fi

if [ $# -eq 0 ]; then
	# Print synopsis
	echo_error "Empty service name."
	exit 1
else
	SERVICE=$1
	
	if [ ! -d "$INFRAC_SERVICES_DIR/$SERVICE" ]; then
		echo_error "Service \"$SERVICE\" does not exist in \"$INFRAC_SERVICES_DIR\"."
		exit 1
	else
		if [ ! -f "$INFRAC_SERVICES_DIR/$SERVICE/main" ]; then
			echo_error "Service \"$SERVICE\" in \"$INFRAC_SERVICES_DIR\" is invalid: main file is missing."
			exit 1
		else
			exit 0
		fi
	fi
fi
